# Generated by Django 5.1.dev20231007045353 on 2023-10-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
